### ISSUE TITLE
Connection Failed

### ISSUE THREAD

**Issue by Slddev** [Tiiffi/mcrcon#65]
I set up rcon on my server and it seems to be working on the server. Trying to connect to the server results to an error "Connection Failed" with no further info. The server is PaperMC 1.16.5. I tried using the launch.bat and the cmd. Both didn't work. Using mcrcon 7.1

**Comment by Tiiffi** [comment]
Hi,

Unfortunately current Windows build of mcrcon doesn't report network errors properly (I should fix this) so it can be harder to debug what's going on. 

Anyway, are you connecting from local network or internet?
Check from server log which ip address is binded to rcon.
Also make sure that rcon port is not blocked by firewall or NAT.

**Comment by Slddev** [comment]
> Hi,
> 
> Unfortunately current Windows build of mcrcon doesn't report network errors properly (I should fix this) so it can be harder to debug what's going on.
> 
> Anyway, are you connecting from local network or internet?
> Check from server log which ip address is binded to rcon.
> Also make sure that rcon port is not blocked by firewall or NAT.

I am connecting outside of my local network
Server Log doesn't show any signs of rcon connection
I turned off my antivirus and firewall.

With all of that in place the same error still happens.

**Comment by Tiiffi** [comment]
>Server Log doesn't show any signs of rcon connection

Does the server show that rcon is actually running?
It should look something like this: `[07:38:26] [RCON Listener #2/INFO]: RCON running on 0.0.0.0:25575`

Make sure that `enable-rcon` is set to `true` in "_server.properties_".

You could also try to use different port for rcon and see if that helps.

**Comment by Slddev** [comment]
> > Server Log doesn't show any signs of rcon connection
> 
> Does the server show that rcon is actually running?
> It should look something like this: `[07:38:26] [RCON Listener #2/INFO]: RCON running on 0.0.0.0:25575`
> 
> Make sure that `enable-rcon` is set to `true` in "_server.properties_".
> 
> You could also try to use different port for rcon and see if that helps.

![image](https://user-images.githubusercontent.com/74999267/107606565-741b9100-6c71-11eb-86eb-505da7872cfd.png)
Yes it is enabled.

**Comment by Piecuuu** [comment]
As seen in the image, the rcon is using the port 23595. Make sure to open this port in your router if you are hosting by yourself.
